import Footer from './compnents/Footer'
import './globals.css'

export const metadata = {
  title: 'Piggyvestclone',
  description: 'Generated by Daniel.js0',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` bg-slate-100 `}>
        {children}
        <Footer/>
        </body>
        
    </html>
  )
}
