import Footer from './compnents/Footer'
import Navbar from './compnents/Navbar'
import './globals.css'
import { Rubik } from 'next/font/google'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Piggyvestclone',
  description: 'Generated by Daniel.js0',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`rubik.className bg-slate-200 `}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
        
    </html>
  )
}
